/**
 * Version constant for Lumiverse Helper
 *
 * This file is auto-generated by update.sh - DO NOT EDIT MANUALLY
 * The version here is used for update checking to avoid manifest caching issues.
 */

/**
 * Current extension version from manifest.json
 * Updated automatically during deployment
 * @type {string}
 */
export const EXTENSION_VERSION = "4.1.0";

/**
 * Export as default for convenience
 * @default EXTENSION_VERSION
 */
export default EXTENSION_VERSION;
